### ISSUE TITLE
I can't add images on product.

### ISSUE THREAD

**Issue by Karibura-Cyber** [arixwap/native-php-shopping-cart#2]
When i upload images it display "Error while move file".

**Comment by arixwap** [comment]
@Karibura-Cyber are you using Mac ?

**Comment by Karibura-Cyber** [comment]
I use windows.

**Comment by arixwap** [comment]
What is your PHP version?

**Comment by Karibura-Cyber** [comment]
php 7.4

**Comment by arixwap** [comment]
This app is tested and run well in PHP 7.1, so maybe some function is not working on latest PHP version

You can try to change PHP version to 7.1 or fix the code by yourself. I believe there some functions might be deprecated arround this line https://github.com/arixwap/native-php-shopping-cart/blob/dd07748c19bbb36ac2d2c9783e3cf9f25640a6c8/app/admin/Product.php#L223-L291

**Comment by Karibura-Cyber** [comment]
Thank you

**Comment by arixwap** [comment]
Hi @Karibura-Cyber 
I just want to know is the issues still exist in your place?

If not so, then I will close this issue

**Comment by Karibura-Cyber** [comment]
I know it's caused by PHP. I set it so I can't upload JPG files, so I can't upload it to the directory.
