### ISSUE TITLE
How to linked the view page with others new file .php page?

### ISSUE THREAD

**Issue by ZyrtecBugisBone** [arixwap/native-php-shopping-cart#3]
i can't find how to show new page into layout main.php, and new file in folder page can't be read or 404 not found when i type name of file inside baseurl()

**Comment by arixwap** [comment]
Where did you create the file?
In root directory or inside `app/` ?

Each file inside `app/` directory will be converted into new subfolder URL.
Example file `app/Cart.php` will be read `http://[YOURLOCALHOST]/cart` as well, and the function name inside those class will be next subfolder URI segment.

Just follow from the existed file controller

**Comment by ZyrtecBugisBone** [comment]
Maaf slow respon dan terimakasih jawabannya, saya pakai bahas indonesia saja. mengenai program ini rencana saya bikinnya jadi program order makanan setiap meja untuk tugas kuliah, dan saya coba buat dalam bentuk satu folder dan saya gandakan seperti di gambar
![Image 1](https://user-images.githubusercontent.com/97608306/150491228-a6a3787d-5814-4e0e-bd0f-d084ad82f554.png)
tapi yang jadi masalahnya file meja1.php sampai meja 4 yang saya bikin tidak bisa memanggil file index.php yang di folder meja1 dengan cara /meja1/index.php. 
Pengetahuan saya masih rendah mengenai coding jadi saya mohon maaf jika kesannya agak menggangu
Terimakasih sebelumnya

**Comment by arixwap** [comment]
Wah bukan begitu caranya..
Seharusnya file kitchen.php, meja1.php, meja2.php, sampai seterusnya dimasukan ke dalam folder [/app](https://github.com/arixwap/native-php-shopping-cart/tree/master/app)

Lalu karena aplikasi ini belum support untuk external CSS, sebaiknya style.css dijadikan inline CSS ke dalam [/view/layout/main.php] (https://github.com/arixwap/native-php-shopping-cart/blob/3b08bc4922e3f5bf31d4dd51ecda25f0bb171dc4/view/layout/main.php)

Karena konsep aplikasi ini sedikit menggunakan MVC (Model View Controller)
